### ISSUE TITLE
zmq problem

### ISSUE THREAD

**Issue by bjost2s** [rnatar609/ASTT-RoboCup-At-Work#4]
if a taskspec is saved or fresh loaded, it is possible to start the timer. If no team is connecting and the user/referee stops the timer a very bad exeption occurs. I think this is an issue of disconnecting a client, which is not there. See output from console from a windows system:

config file D:\Users\Beate\RobocupAtWork\config.txt exists.
background file D:\Users\Beate\RobocupAtWork\backgroundMap.png exists.
127.0.1.1
11111
Server socket created: org.zeromq.ZMQ$Socket@834af6 ipAddress: 127.0.1.1 port: 11111
Server thread started... 
Waiting for Client Requests on socket... org.zeromq.ZMQ$Socket@834af6
competition BNT
Valid place pattern: (D0|D1|D2|O1|O2|O3|S1|S2|S3|T2|T4|T6)
Valid orientation pattern: (N|S|W|E)
Valid pause pattern: (1|2|3|4|5)
Valid triplet pattern ((D0|D1|D2|O1|O2|O3|S1|S2|S3|T2|T4|T6)\,(N|S|W|E)\,(1|2|3|4|5))
competition BMT
competition BTT
competition CTT
D:\RobocupAtWork_2012-06-16_21-22-20.log
Client Disconnected
# 
# A fatal error has been detected by the Java Runtime Environment:
# 
# Internal Error (0x40000015), pid=2492, tid=2852
# 
# JRE version: 7.0_04-b22
# Java VM: Java HotSpot(TM) Client VM (23.0-b21 mixed mode, sharing windows-x86 )
# Problematic frame:
# C  [KERNELBASE.dll+0xb9bc]  RaiseException+0x58
# 
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
# 
# An error report file with more information is saved as:
# D:\Users\Beate\git\ASTT-RoboCup-At-Work\RefereePkg\hs_err_pid2492.log
# 
# If you would like to submit a bug report, please visit:
# http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
# 

Assertion failed: ok (......\src\mailbox.cpp:84)

**Comment by aalnaw2s** [comment]
hi 

Yes i faced the same issue, also this is reflected on the logging entries which list the disconnection of the client while there is no client already, So i think the timer should be activated only when there is a client connected to the system and the log should be inserted after the connection is established.

**Comment by bjost2s** [comment]
The timer could solve this problem. But the client doesn't have to connect to the server before the timer starts. They have to do it by no later than the end of the setup time. If the client does not connect to the server, the referee should be able to cancel the competition by hand with timer stop. I think the server knows, if a client is connected, so there must be an additional check for the connection before disconnecting (?)

**Comment by janpaulus** [comment]
I fixed the issue by checking if a connection is active or not
