### ISSUE TITLE
Timer Start/Stop Button Enable/Disable in CTT mode

### ISSUE THREAD

**Issue by rnatar609** [rnatar609/ASTT-RoboCup-At-Work#5]
In CTT mode, there is a small issue with the enabling and Disabling of Timer Start/Stop Button.....

The Timer Star/Stop button is right now enabled even before the triplets are sent to the client, this bug enables the referee to start the timer though no triplets have been sent to the client....

One more issue is that the timer start/Stop button is not disabled when the competition finished button is pressed.

**Comment by janpaulus** [comment]
this is correct like this!
